include: package:lint/analysis_options.yaml

analyzer:
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
  exclude:
    - lib/injection.config.dart
    - lib/presentation/routes/router.gr.dart
    - lib/application/*/*.freezed.dart
    - lib/application/*/*/*.freezed.dart
    - lib/domain/*/*.freezed.dart
    - lib/generated_plugin_registrant.dart
    - lib/domain/*/*.g.dart

linter:
  rules:
    directives_ordering: false
    constant_identifier_names: false
