targets:
  $default:
    builders:
      auto_route_generator|autoRouteGenerator:
        enabled: true
        generate_for:
          include:
            - lib/presentation/routes/router.dart

      # json_serializable:
      #   enabled: false

      # freezed|freezed:
      #   enabled: false

      # injectable_generator|injectable_builder:
      #   enabled: false

      # injectable_generator|injectable_config_builder:
      #   enabled: false
