targets:
  $default:
    builders:
      auto_route_generator|autoRouteGenerator:
        enabled: true

      json_serializable:
        enabled: true

      freezed|freezed:
        enabled: true

      injectable_generator|injectable_builder:
        enabled: true

      injectable_generator|injectable_config_builder:
        enabled: true
