name: flutter_share
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animator: ^3.1.0
  another_flushbar: ^1.10.28
  auto_route: ^3.2.2
  bloc: ^7.2.0
  cached_network_image: ^3.2.0
  camera: ^0.9.4+10
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_hooks: ^0.18.2
  flutter_local_notifications: ^9.2.0
  freezed_annotation: ^1.1.0
  geocoding: ^2.0.2
  geolocator: ^8.1.1
  get_it: ^7.2.0
  google_sign_in: ^5.2.3
  image: ^3.1.1
  image_picker: ^0.8.4+6
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  rxdart: ^0.27.3
  timeago: ^3.2.1
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_auth.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf