name: flutter_share
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animator: ^3.0.0
  another_flushbar: ^1.10.24
  auto_route: ^2.2.0
  cached_network_image: ^3.0.0
  camera: ^0.8.1
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^8.1.0
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.2
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  get_it: ^7.1.4
  google_sign_in: ^5.0.3
  image: ^3.0.2
  image_picker: ^0.7.5+2
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  path_provider: ^2.0.1
  rxdart: ^0.27.1
  timeago: ^3.0.2
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.5
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_auth.png
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
